In [1]:
# Import dependencies
from bs4 import BeautifulSoup as soup
from splinter import Browser
import pandas as pd
import time

In [2]:
url_list_2021 = ['https://www.pgatour.com/content/pgatour/stats/stat.02567.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02674.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.101.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02341.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.496.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02568.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.103.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02437.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.190.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.199.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.431.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.437.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02569.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.111.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.130.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02564.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.413.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.426.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.104.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.119.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02414.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02415.y2021.html',
'https://www.pgatour.com/content/pgatour/stats/stat.109.y2021.html']

In [ ]:
url_list_2020 = ['https://www.pgatour.com/content/pgatour/stats/stat.02567.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02674.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.101.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02341.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.496.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02568.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.103.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02437.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.190.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.199.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.431.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.437.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02569.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.111.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.130.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02564.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.413.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.426.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.104.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.119.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02414.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02415.y2020.html',
'https://www.pgatour.com/content/pgatour/stats/stat.109.y2020.html']

In [ ]:
url_list_2019 = ['https://www.pgatour.com/content/pgatour/stats/stat.02567.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02674.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.101.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02341.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.496.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02568.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.103.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02437.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.190.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.199.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.431.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.437.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02569.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.111.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.130.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02564.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.413.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.426.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.104.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.119.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02414.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02415.y2019.html',
'https://www.pgatour.com/content/pgatour/stats/stat.109.y2019.html']

In [ ]:
url_list_2018 = ['https://www.pgatour.com/content/pgatour/stats/stat.02567.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02674.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.101.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02341.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.496.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02568.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.103.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02437.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.190.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.199.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.431.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.437.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02569.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.111.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.130.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02564.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.413.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.426.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.104.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.119.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02414.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02415.y2018.html',
'https://www.pgatour.com/content/pgatour/stats/stat.109.y2018.html']

In [ ]:
url_list_2017 = ['https://www.pgatour.com/content/pgatour/stats/stat.02567.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02674.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.101.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02341.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.496.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02568.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.103.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02437.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.190.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.199.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.431.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.437.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02569.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.111.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.130.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02564.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.413.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.426.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.104.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.119.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02414.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.02415.y2017.html',
'https://www.pgatour.com/content/pgatour/stats/stat.109.y2017.html']

In [3]:
# Start out dataframes as empty lists (IDs listed in golfstats_FINAL_Excel file)
df1 = []
df2 = []
df3 = []
df4 = []
df5 = []
df6 = []
df7 = []
df8 = []
df9 = []
df10 = []
df11 = []
df12 = []
df13 = []
df14 = []
df15 = []
df16 = []
df17 = []
df18 = []
df19 = []
df20 = []
df21 = []
df22 = []
df23 = []
df24 = []
df25 = []
df26 = []
df27 = []
df28 = []
df29 = []
df30 = []
df31 = []
df32 = []
df33 = []
df34 = []
df35 = []
df36 = []
df37 = []
df38 = []
df39 = []
df40 = []
df41 = []
df42 = []
df43 = []
df44 = []
df45 = []
df46 = []
df47 = []
df48 = []
df49 = []
df50 = []
df51 = []
df52 = []
df53 = []
df54 = []
df55 = []
df56 = []
df57 = []
df58 = []
df59 = []
df60 = []
df61 = []
df62 = []
df63 = []
df64 = []
df65 = []
df66 = []
df67 = []
df68 = []
df69 = []
df70 = []
df71 = []
df72 = []
df73 = []
df74 = []
df75 = []
df76 = []
df77 = []
df78 = []
df79 = []
df80 = []
df81 = []
df82 = []
df83 = []
df84 = []
df85 = []
df86 = []
df87 = []
df88 = []
df89 = []
df90 = []
df91 = []
df92 = []
df93 = []
df94 = []
df95 = []
df96 = []
df97 = []
df98 = []
df99 = []
df100 = []
df101 = []
df102 = []
df103 = []
df104 = []
df105 = []
df106 = []
df107 = []
df108 = []
df109 = []
df110 = []
df111 = []
df112 = []
df113 = []
df114 = []
df115 = []


dataframe_2021 = [df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,df22,d23]
dataframe_2020 = [df24,df25,df26,df27,df28,df29,df30,df31,df32,df33,df34,df35,df36,df37,df38,df39,df40,df41,df42,df43,df44,df45,df46]
dataframe_2019 = [df47,df48,df49,df50,df51,df52,df53,df54,df55,df56,df57,df58,df59,df60,df61,df62,df63,df64,df65,df66,df67,df68,df69]
dataframe_2018 = [df70,df71,df72,df73,df74,df75,df76,df77,df78,df79,df80,df81,df82,df83,df84,df85,df86,df87,df88,df89,df90,df91,df92]
dataframe_2017 = [df93,df94,df95,df96,df97,df98,df99,df100,df101,df102,df103,df104,df105,df106,df107,df108,df109,df110,df111,df112,df113,df114,df115]

In [5]:
# Scrape 2021
for index, url in enumerate(url_list_2021):
    
    # Set the executable path and initialize the chrome browser in splinter
    executable_path = {'executable_path': 'chromedriver'}
    browser = Browser('chrome', **executable_path)
    
    # Pause 5 seconds so as not to overwhelm server
    time.sleep(5)
    
    # Visit URL, parse, find table
    browser.visit(url)
    browser.is_element_present_by_css("ul.item_list li.slide", wait_time=1)
    html = browser.html
    golf_soup = soup(html, 'html.parser')
    table = golf_soup.find('table', class_='table-styled')
    
    # Find rows and headings
    table_rows = table.find('tbody').find_all('tr')
    table_headings = table.find('thead').find_all('th')
    
    # Strip column name text and append to df
    column_names = [cm.text.strip() for cm in table_headings]
    dataframe_2021[index].append(column_names)
    
    # Strip text in rows and append to df
    for tr in table_rows:
        rows = [tr.text.strip() for tr in tr.find_all('td')]
        dataframe_2021[index].append(rows)
    
    # Convert list to pandas dataframe
    dataframe_2021[index]= pd.DataFrame(dataframe_2021[index])
    
    # Promote headers
    header = dataframe_2021[index].iloc[0]
    dataframe_2021[index] = dataframe_2021[index][1:]
    dataframe_2021[index].columns = header
    
    # Set Index equal to PLAYER NAME
    dataframe_2021[index] = dataframe_2021[index].set_index('PLAYER NAME')
    
    # Quit browser
    browser.quit()

In [10]:
dataframe_2021[0]

,RANK THIS WEEK,RANK LAST WEEK,ROUNDS,STATUS,PAR 3 AVG,TOTAL PAR
PLAYER NAME,,,,,,
Pat Perez,1,T7,64,-21,2.92,774
Stewart Cink,2,1,50,-19,2.90,594
Justin Rose,3,T11,30,-15,2.88,372
Charley Hoffman,4,T2,69,-14,2.95,840
Tony Finau,5,T7,55,-13,2.94,636
...,...,...,...,...,...,...
Hudson Swafford,T210,T205,46,+30,3.16,546
Adam Long,213,209,55,+34,3.16,648
Charles Howell III,214,211,50,+37,3.19,600
Hunter Mahan,T215,213,42,+42,3.25,510
Beau Hossler,T215,212,54,+42,3.19,654

In [6]:
# df0 = dataframe[0][["PAR 3 BIRDIES OR BETTER"]]
# df1 = dataframe[1][["PAR 4 BIRDIES OR BETTER"]]

In [7]:
# df0.join(df1)

0                  PAR 3 BIRDIES OR BETTER PAR 4 BIRDIES OR BETTER
PLAYER NAME
Justin Rose                             26                      53
Stewart Cink                            41                     105
Justin Thomas                           34                     102
Dustin Johnson                          27                      72
Harry Higgs                             38                      91
...                                    ...                     ...
Ben Martin                               8                      42
Byeong Hun An                           13                      81
Jonathan Byrd                            7                      41
Charles Howell III                      10                      81
Lee Westwood                             6                      50

[216 rows x 2 columns]